Repository Smurfs-village/Buddy-Bee, pull requests merged in 2024-07, with the labels that each got.

#101 마이페이지 수정
  src/img/myPage_flower.svg
  src/views/ProfilePage/MyProfile.css
  src/views/ProfilePage/MyProfile.js
  src/views/ProfilePage/ProfilePage.js
Labels: 초기

#108 created UI configuration in MyPosts & MyProfile UI modification
  src/img/hero_concert.jpg
  src/img/jeonsomi.jpg
  src/img/kissOfLife_concert.jpg
  src/img/right_arrow.svg
  src/img/shinee_concert.jpg
  src/img/writtenPosts_img.svg
  src/views/ProfilePage/MyPosts.css
  src/views/ProfilePage/MyPosts.js
  src/views/ProfilePage/MyProfile.css
  src/views/ProfilePage/MyProfile.js
  src/views/ProfilePage/ProfilePage.js
Labels: 이거고쳐줘, css 수정, 초기

#134 Participated projects
  src/components/Common/Aside.css
  src/components/Common/Aside.js
  src/components/Common/ListCard.css
  src/views/ProfilePage/Bookmarks.js
  src/views/ProfilePage/MyPosts.css
  src/views/ProfilePage/MyPosts.js
  src/views/ProfilePage/MyProfile.css
  src/views/ProfilePage/MyProfile.js
  src/views/ProfilePage/ParticipatedProjects.css
  src/views/ProfilePage/ParticipatedProjects.js
  src/views/ProfilePage/ProfilePage.css
Labels: 초기

#143 회원 가입 페이지 추가_Add Register page and dropdown in login page
  src/views/LoginPage/LoginPage.css
  src/views/LoginPage/LoginPage.js
  src/views/RegisterPage/RegisterPage.css
  src/views/RegisterPage/RegisterPage.js
Labels: 추가, 초기

#148 로그인/회원가입 페이지 레이아웃 분리_split component for login/register page
  src/components/Layout/LoginPageLayout.css
  src/components/Layout/LoginPageLayout.js
  src/views/LoginPage/LoginPage.css
  src/views/LoginPage/LoginPage.js
  src/views/RegisterPage/RegisterPage.css
  src/views/RegisterPage/RegisterPage.js
Labels: 추가, css 수정

#150 Bookmarks 추가, 수정 사항
  src/components/Common/Aside.css
  src/components/Common/Aside.js
  src/img/OOH1.jpg
  src/img/OOH2.jpg
  src/img/accompany1.jpg
  src/img/accompany2.jpeg
  src/img/accompany3.jpeg
  src/img/birdayParty1.jpg
  src/img/blackpink_concert.jpg
  src/img/bts_concert.jpg
  src/img/demand_survey1.png
  src/img/finished_project1.jpg
  src/img/karina_concert.jpg
  src/img/marklee.jpg
  src/img/nctDream_concert.jpg
  src/img/riize1.jpg
  src/img/seventeen_concert.jpg
  src/img/sheonoo.jpg
  src/img/taemin.jpg
  src/img/treasure_concert.jpg
  src/views/ProfilePage/Bookmarks.css
  src/views/ProfilePage/Bookmarks.js
  src/views/ProfilePage/Common.css
  src/views/ProfilePage/Common.js
  src/views/ProfilePage/MyPosts.js
  src/views/ProfilePage/MyProfile.css
  src/views/ProfilePage/MyProfile.js
  src/views/ProfilePage/ParticipatedProjects.css
  src/views/ProfilePage/ParticipatedProjects.js
  src/views/ProfilePage/ProfilePage.css
Labels: 추가, 헤얿, 확인요망, css 수정

#155 목록 카드 페이지 최신순/인기순 정렬 기능 추가_Implement card sorting feature
  src/components/Common/ListCard.css
  src/components/Common/ListCard.js
  src/components/Layout/ProjectListPageLayout.css
  src/components/Layout/ProjectListPageLayout.js
Labels: 추가, css 수정

#164 인증하기 버튼 UI, 삭제 기능 구현
  src/img/bts.jpg
  src/img/twice_concert.jpg
  src/views/ProfilePage/Bookmarks.css
  src/views/ProfilePage/Bookmarks.js
  src/views/ProfilePage/Common.css
  src/views/ProfilePage/MyPosts.js
  src/views/ProfilePage/MyProfile.css
  src/views/ProfilePage/MyProfile.js
  src/views/ProfilePage/ParticipatedProjects.js
Labels: 추가, 확인요망

#167 Port change 5000번 포트 5001로 수정
  frontend/src/api/api.js
  frontend/src/components/Common/Editor.js
  frontend/src/components/Layout/CreatePageLayout.js
  server/server.js
Labels: 버그

#169 페이지네이션 컴포넌트 /목록 페이지 페이지네이션 추가_ Pagination feature added
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Common/ListCard.js
  frontend/src/components/Common/Pagination.css
  frontend/src/components/Common/Pagination.js
  frontend/src/components/Layout/ProjectListPageLayout.css
  frontend/src/components/Layout/ProjectListPageLayout.js
Labels: 추가, css 수정

#170 CreatePageLayout css modify
  frontend/src/components/Layout/CreatePageLayout.css
  frontend/src/components/Layout/CreatePageLayout.js
Labels: css 수정

#174 Sub Navbar 컴포넌트 분리/필터 기능_split sub nav to component, add filter function
  frontend/src/components/Common/ListCard.css
  frontend/src/components/Common/ListCard.js
  frontend/src/components/Layout/ProjectListPageLayout.css
  frontend/src/components/Layout/ProjectListPageLayout.js
  frontend/src/components/Layout/SubNav.css
  frontend/src/components/Layout/SubNav.js
Labels: 추가, css 수정, 세팅

#191 Scrap button 구현, 세부 css 조정
  frontend/src/components/Common/Aside.css
  frontend/src/components/Layout/ProjectListPageLayout.js
  frontend/src/views/ProfilePage/Bookmarks.css
  frontend/src/views/ProfilePage/Bookmarks.js
  frontend/src/views/ProfilePage/Common.css
  frontend/src/views/ProfilePage/Common.js
  frontend/src/views/ProfilePage/MyPosts.js
  frontend/src/views/ProfilePage/MyProfile.css
  frontend/src/views/ProfilePage/MyProfile.js
  frontend/src/views/ProfilePage/ParticipatedProjects.js
  frontend/src/views/ProfilePage/ProfilePage.css
Labels: 추가, css 수정

#200 헤더 햄버거 기능 프로토_Header hamburger func proto
  frontend/src/components/Header/Header.css
  frontend/src/components/Header/Header.js
  frontend/src/img/create_icon.svg
  frontend/src/img/search_icon.svg
Labels: 추가, css 수정

#201 main-page to list-page modify
  frontend/src/components/Layout/ProjectListPageLayout.js
  frontend/src/views/MainPage/MainPage.js
Labels: 문서, 확인요망

#203 My page need help
  frontend/src/views/ProfilePage/Bookmarks.js
  frontend/src/views/ProfilePage/Common.css
  frontend/src/views/ProfilePage/Common.js
  frontend/src/views/ProfilePage/MyPosts.js
  frontend/src/views/ProfilePage/MyProfile.css
  frontend/src/views/ProfilePage/MyProfile.js
  frontend/src/views/ProfilePage/ParticipatedProjects.js
Labels: 헤얿, 이거고쳐줘

#206 만들기 / 디테일 페이지 css 수정
  frontend/src/assets/fonts/PretendardVariable.woff2
  frontend/src/components/Layout/CreatePageLayout.css
  frontend/src/components/Layout/CreatePageLayout.js
  frontend/src/img/share-icon.svg
  frontend/src/views/ProjectDetailPage/DetailButton.css
  frontend/src/views/ProjectDetailPage/DetailButton.js
  frontend/src/views/ProjectDetailPage/DetailContent.css
  frontend/src/views/ProjectDetailPage/DetailHashtag.css
  frontend/src/views/ProjectDetailPage/DetailProfile.css
  frontend/src/views/ProjectDetailPage/DetailTitle.css
  frontend/src/views/ProjectDetailPage/ProjectDetailFundingUser.js
  frontend/src/views/ProjectDetailPage/ProjectDetailPage.css
  frontend/src/views/ProjectDetailPage/ProjectDetailPageFunding.css
  frontend/src/views/ProjectDetailPage/ProjectDetailPageFunding.js
  frontend/src/views/ProjectDetailPage/ProjectDetailPageWith.css
  frontend/src/views/ProjectDetailPage/ProjectDetailPageWith.js
  frontend/src/views/ProjectDetailPage/ProjectDetailWithUser.js
Labels: css 수정

#223 Profile page card back
  frontend/src/components/Common/Aside.css
  frontend/src/views/ProfilePage/Common.css
  frontend/src/views/ProfilePage/MyPosts.js
  server/controllers/projectController.js
  server/routes/projectRoutes.js
Labels: 추가, css 수정, 백엔드

#224 레이아웃 헤더 햄버거 메뉴 수정_Header hamburger menu edited
  frontend/src/components/Header/Header.css
  frontend/src/components/Header/Header.js
Labels: 추가, css 수정

#227 list-hashtag-bug-fix
  frontend/src/components/Common/ListCard.js
Labels: 버그

#235 feat: add Subnav all view button (#220)
  frontend/src/components/Layout/SubNav.css
  frontend/src/components/Layout/SubNav.js
Labels: 문서, 추가

#237 feat : profile-participateproject-back-connect #236
  frontend/src/views/ProfilePage/ParticipatedProjects.js
  server/controllers/projectController.js
  server/routes/projectRoutes.js
Labels: 백엔드

#242 feat: Add with-Button by other-user-persepective & deleted with-Butto…
  frontend/src/views/ProjectDetailPage/DetailFundingStatus.css
  frontend/src/views/ProjectDetailPage/ProjectDetailPageFunding.js
  frontend/src/views/ProjectDetailPage/ProjectDetailPageWith.js
  frontend/src/views/ProjectDetailPage/ProjectDetailWithUser.js
Labels: 추가, css 수정

#245 햄버거 메뉴 2중 드롭 다운 구현_Feature/header hamburger menu
  frontend/src/components/Header/Header.css
  frontend/src/components/Header/Header.js
Labels: 추가, css 수정

#246 feat : profile-bookmarks-back-connect 나의 꿀단지 페이지 백엔드 추가 #239
  frontend/src/views/ProfilePage/Bookmarks.js
  server/controllers/projectController.js
  server/routes/projectRoutes.js
Labels: 추가, 백엔드

#247 햄버거 메뉴 search input 버그 수정_Bug/header hamburger menu
  frontend/src/components/Header/Header.js
Labels: 버그

#250 fix : overlay issue, add animation to drop down btn (#248, #249)
  frontend/src/components/Header/Header.css
Labels: 추가, css 수정

#264 feat : profile-page-card-route-add 마이페이지 카드들 라우트 연결 #259
  frontend/src/views/ProfilePage/Bookmarks.js
  frontend/src/views/ProfilePage/MyPosts.js
  frontend/src/views/ProfilePage/ParticipatedProjects.js
Labels: 추가

#270 헤더 라우트 연결/css 변경_Feature/header dropdown route
  frontend/src/components/Header/Header.css
  frontend/src/components/Header/Header.js
  frontend/src/img/nav_logo.svg
Labels: 추가, css 수정

#271 Scrap bug fix
  frontend/src/components/Common/ListCard.js
  frontend/src/views/ProjectDetailPage/DetailButton.js
  frontend/src/views/ProjectDetailPage/ProjectDetailFundingUser.css
  frontend/src/views/ProjectDetailPage/ProjectDetailFundingUser.js
  frontend/src/views/ProjectDetailPage/ProjectDetailWithUser.css
  frontend/src/views/ProjectDetailPage/ProjectDetailWithUser.js
Labels: 버그

#272 햄버거 버튼 버그 해결_bug/ fix header-hamburger big (#234)
  frontend/src/components/Header/Header.js
Labels: 버그

#273 Create page bug hot fix
  frontend/src/components/Layout/CreatePageLayout.js
Labels: 버그, 추가

#279 로그인 페이지 모바일 뷰_login mobile view
  frontend/src/components/Layout/LoginPageLayout.css
  frontend/src/views/LoginPage/LoginPage.css
Labels: css 수정, 세팅

#280 Detail page participate back
  frontend/src/views/ProjectDetailPage/ProjectDetailFundingUser.js
  frontend/src/views/ProjectDetailPage/ProjectDetailWithUser.js
  server/controllers/projectController.js
  server/routes/projectRoutes.js
Labels: 백엔드

#283 푸터 수정_feature : give footer min-width (#281)
  frontend/src/components/Footer/Footer.css
Labels: css 수정

#285 feat : 참가 버튼 동작에 정보 추가 #282
  frontend/src/views/ProjectDetailPage/DetailAgree.js
  frontend/src/views/ProjectDetailPage/DetailUserInfo.js
  frontend/src/views/ProjectDetailPage/ProjectDetailFundingUser.js
  frontend/src/views/ProjectDetailPage/ProjectDetailWithUser.js
  server/controllers/projectController.js
Labels: 백엔드

#286 feat: 목록 페이지 타이틀 표시 (#219)
  frontend/src/components/Layout/ProjectListPageLayout.js
Labels: 추가

#288 Header 모바일 뷰 높이 변경_css fix/header mobile height
  frontend/src/components/Header/Header.css
  frontend/src/components/Header/Header.js
Labels: css 수정

#290 Update project status
  server/controllers/projectController.js
  server/package-lock.json
  server/package.json
  server/scripts/updateProjectStatus.js
  server/server.js
Labels: 백엔드

#292 bug-fix: 동행 참여하기 옵션 선택 #291
  frontend/src/views/ProjectDetailPage/DetailUserInfo.js
  frontend/src/views/ProjectDetailPage/ProjectDetailFundingUser.js
  server/controllers/projectController.js
Labels: 버그, 백엔드

#294 feat : 페이지 접근 제한
  frontend/src/App.js
  frontend/src/components/Routing/ProtectedRoute.js
  frontend/src/views/ProjectDetailPage/ProjectDetailFundingUser.js
  frontend/src/views/ProjectDetailPage/ProjectDetailWithUser.js
Labels: 백엔드

#296 feat: myPage-mobile UI configurating
  frontend/src/components/Common/Aside.css
  frontend/src/components/Common/Top.css
  frontend/src/views/ProfilePage/Common.css
  frontend/src/views/ProfilePage/MyProfile.css
  frontend/src/views/ProfilePage/MyProfile.js
  frontend/src/views/ProfilePage/ProfilePage.css
Labels: 추가, css 수정, 초기

#300 bug-fix : fix header dropdown-profile-btn bug (#299)
  frontend/src/components/Header/Header.js
Labels: 버그

#303 fix : login-접근제한 버그 수정
  frontend/src/App.js
  frontend/src/components/Routing/ProtectedRoute.js
  frontend/src/contexts/AuthContext.js
Labels: 버그

#305 fix : 로그아웃 할 때 로컬스토리지가 남아있는 버그 수정 #304
  frontend/src/components/Header/Header.js
  frontend/src/components/Routing/ProtectedRoute.js
  frontend/src/contexts/AuthContext.js
Labels: 버그

#306 회원 가입 페이지 수정_feature/128 register mobile view
  frontend/src/api/api.js
  frontend/src/components/Footer/Footer.css
  frontend/src/components/Layout/BackGroundGrid.css
  frontend/src/components/Layout/Layout.css
  frontend/src/components/Layout/LoginPageLayout.css
  frontend/src/views/LoginPage/LoginPage.css
  frontend/src/views/RegisterPage/RegisterPage.css
  frontend/src/views/RegisterPage/RegisterPage.js
Labels: 버그, 추가, css 수정

#308 My page right container
  frontend/src/components/Common/Aside.css
  frontend/src/components/Common/Top.css
  frontend/src/components/Footer/Footer.css
  frontend/src/views/ProfilePage/Common.css
  frontend/src/views/ProfilePage/MyProfile.css
  frontend/src/views/ProfilePage/ProfilePage.css
Labels: css 수정

#310 Detail back user connect
  frontend/src/views/ProjectDetailPage/DetailProfile.css
  frontend/src/views/ProjectDetailPage/DetailProfile.js
  frontend/src/views/ProjectDetailPage/ProjectDetailFundingUser.js
  frontend/src/views/ProjectDetailPage/ProjectDetailWithUser.js
  server/controllers/projectController.js
  server/routes/projectRoutes.js
Labels: 추가, 백엔드

#311 feat : 디테일 페이지 프로필 샘플 이미지 추가 #309
  frontend/src/views/ProjectDetailPage/DetailProfile.js
  frontend/src/views/ProjectDetailPage/ProjectDetailPageFunding.js
  frontend/src/views/ProjectDetailPage/ProjectDetailPageWith.js
  frontend/src/views/ProjectDetailPage/ProjectDetailWithUser.js
  server/controllers/projectController.js
Labels: 추가, 백엔드

#313 feat: myPage myProfile category mobile UI edited
  frontend/src/components/Common/Aside.css
  frontend/src/components/Common/Aside.js
  frontend/src/components/Common/Top.css
  frontend/src/views/ProfilePage/Common.css
  frontend/src/views/ProfilePage/MyProfile.css
  frontend/src/views/ProfilePage/ProfilePage.css
Labels: css 수정

#314 feat : 디테일 페이지 참여자 수 불러오기 #312
  frontend/src/views/ProjectDetailPage/ProjectDetailFundingUser.js
  frontend/src/views/ProjectDetailPage/ProjectDetailPageFunding.js
  frontend/src/views/ProjectDetailPage/ProjectDetailPageWith.js
  frontend/src/views/ProjectDetailPage/ProjectDetailWithUser.js
Labels: 추가, 백엔드

#315 feat: myPage-CommonView(MyPosts & ParticipatedProjects) mobileView
  frontend/src/views/ProfilePage/Common.css
Labels: css 수정

#317 feat: Mainpage mobile css
  frontend/src/views/MainPage/MainPage.css
Labels: 헤얿, 이거고쳐줘, css 수정

#319 fix : profile-img-bug-hot-fix
  frontend/src/views/ProjectDetailPage/ProjectDetailWithUser.js
Labels: 버그

#320 myPage-honeyPots mobileView configurating & several modifications
  frontend/src/components/Common/Aside.css
  frontend/src/views/ProfilePage/Bookmarks.css
  frontend/src/views/ProfilePage/Bookmarks.js
  frontend/src/views/ProfilePage/Common.css
  frontend/src/views/ProfilePage/ProfilePage.css
Labels: css 수정

#321 동행 페이지 모바일 뷰_feature/125 create with page mobile
  frontend/src/components/Layout/CreatePageLayout.css
  frontend/src/components/Layout/CreatePageLayout.js
  frontend/src/components/Layout/PageLayout.css
Labels: 추가, css 수정

#330 펀딩 글 작성 페이지 모바일 뷰_feature/322 create funding mobile view
  frontend/src/components/Layout/CreatePageLayout.css
  frontend/src/components/Layout/CreatePageLayout.js
Labels: 추가, css 수정

#331 myPage mobileView modification & mockImg added
  frontend/src/views/ProfilePage/Bookmarks.js
  frontend/src/views/ProfilePage/MyPosts.js
  frontend/src/views/ProfilePage/MyProfile.css
  frontend/src/views/ProfilePage/ParticipatedProjects.js
Labels: 추가, css 수정

#335 feat: myPage myPosts & ParticipatedProjects mobile-view edited
  frontend/src/components/Common/Top.css
  frontend/src/views/ProfilePage/Bookmarks.css
  frontend/src/views/ProfilePage/Common.css
Labels: css 수정

#337 Edit button in detail
  frontend/src/App.js
  frontend/src/components/Layout/CreatePageLayout.js
  frontend/src/views/ProjectDetailPage/ProjectDetailPageFunding.js
  frontend/src/views/ProjectDetailPage/ProjectDetailPageWith.js
  server/controllers/projectController.js
  server/routes/projectRoutes.js
Labels: 백엔드

#340 feat: SignupPage - space error, limit letter
  frontend/src/views/RegisterPage/RegisterPage.js
Labels: 추가

#341 fix : 디테일 페이지 해시테그 출력 오류 #339
  frontend/src/views/ProjectDetailPage/ProjectDetailFundingUser.js
  frontend/src/views/ProjectDetailPage/ProjectDetailPageFunding.js
  frontend/src/views/ProjectDetailPage/ProjectDetailPageWith.js
Labels: 버그

#343 feat : 작성한글 페이지 카드 삭제 버튼 #260
  frontend/src/views/ProfilePage/MyPosts.js
  frontend/src/views/ProfilePage/ParticipatedProjects.js
  server/controllers/projectController.js
  server/routes/projectRoutes.js
Labels: 추가, 백엔드

#344 카드 목록 페이지 모바일 구현_feature/129 cardlist page mobile
  frontend/src/components/Common/ListCard.css
  frontend/src/components/Common/ListCard.js
  frontend/src/components/Layout/PageLayout.css
  frontend/src/components/Layout/ProjectListPageLayout.css
  frontend/src/components/Layout/SubNav.css
Labels: css 수정

#347 feat : 로그인을 오래 지속했을 시 토큰 만료 이슈 #332
  frontend/src/api/api.js
  frontend/src/utils/token.js
  server/controllers/authController.js
Labels: 추가, 기능 개선

#348 Main page status filter
  frontend/src/components/Layout/ProjectListPageLayout.js
  frontend/src/views/MainPage/MainPage.js
Labels: 추가

#351 feat: myPage myPosts and ParticipatedProjects finishedProjectsCard op…
  frontend/src/views/ProfilePage/Common.css
  frontend/src/views/ProfilePage/MyPosts.js
  frontend/src/views/ProfilePage/ParticipatedProjects.js
  frontend/src/views/ProfilePage/ProfilePage.js
Labels: css 수정

#352 Main page UI mobile view
  frontend/src/views/MainPage/Card.js
  frontend/src/views/MainPage/MainPage.css
  frontend/src/views/MainPage/MainPage.js
Labels: 추가, css 수정

#356 feat : 메인페이지 모바일 카드 사이즈 수정 #316 #354
  frontend/src/views/MainPage/Card.js
  frontend/src/views/MainPage/MainPage.css
Labels: 버그, 추가, css 수정

#357 feat:myPage honeyPot css edit
  frontend/src/components/Common/Aside.css
  frontend/src/views/ProfilePage/Bookmarks.css
  frontend/src/views/ProfilePage/Bookmarks.js
  frontend/src/views/ProfilePage/ProfilePage.css
Labels: css 수정

#358 feat: ListPage-grid css
  frontend/src/components/Common/ListCard.css
  frontend/src/components/Layout/PageLayout.css
Labels: css 수정

#360 Fix : 마이페이지 종료된 프로젝트 페이지네이션 적용 오류 #359
  frontend/src/views/ProfilePage/Bookmarks.js
Labels: 버그

#361 Fix : 참여중인 프로젝트도 페이지네이션 수정
  frontend/src/views/ProfilePage/ParticipatedProjects.js
Labels: 버그

#364 feat: CreatePage - add the Enter hashtag feature
  frontend/src/components/Layout/CreatePageLayout.js
Labels: 추가, 기능 개선

#365 myPage-MyProfile cloudImg and buttons animation effects added
  frontend/src/components/Common/Top.css
  frontend/src/views/ProfilePage/MyProfile.css
Labels: css 수정

#370 feat : animation add #366 #367 #368 #369
  frontend/src/views/MainPage/MainPage.css
  frontend/src/views/MainPage/MainPage.js
Labels: 추가, css 수정

#371 feat:myPage Common & Bookmarks cards and buttons animation added
  frontend/src/components/Common/Top.css
  frontend/src/views/ProfilePage/Bookmarks.css
  frontend/src/views/ProfilePage/Common.css
  frontend/src/views/ProfilePage/MyProfile.css
Labels: css 수정

#375 디테일 페이지 css 수정/모바일 뷰 UI_Feature/126 detail page mobile
  frontend/src/components/Layout/PageLayout.css
  frontend/src/views/ProjectDetailPage/DetailAgree.css
  frontend/src/views/ProjectDetailPage/DetailButton.css
  frontend/src/views/ProjectDetailPage/DetailContent.css
  frontend/src/views/ProjectDetailPage/DetailFundingStatus.css
  frontend/src/views/ProjectDetailPage/DetailFundingStatus.js
  frontend/src/views/ProjectDetailPage/DetailHashtag.css
  frontend/src/views/ProjectDetailPage/DetailParticipate.css
  frontend/src/views/ProjectDetailPage/DetailProfile.css
  frontend/src/views/ProjectDetailPage/DetailTitle.css
  frontend/src/views/ProjectDetailPage/DetailUserInfo.css
  frontend/src/views/ProjectDetailPage/ProjectDetailFundingUser.css
  frontend/src/views/ProjectDetailPage/ProjectDetailFundingUser.js
  frontend/src/views/ProjectDetailPage/ProjectDetailPage.css
  frontend/src/views/ProjectDetailPage/ProjectDetailPageFunding.css
  frontend/src/views/ProjectDetailPage/ProjectDetailPageFunding.js
  frontend/src/views/ProjectDetailPage/ProjectDetailPageWith.css
  frontend/src/views/ProjectDetailPage/ProjectDetailPageWith.js
  frontend/src/views/ProjectDetailPage/ProjectDetailWithUser.css
  frontend/src/views/ProjectDetailPage/ProjectDetailWithUser.js
Labels: 추가, css 수정

#377 feat: CreatePage - add the Enter option feature (#376)
  frontend/src/components/Layout/CreatePageLayout.js
Labels: 추가, 기능 개선

#378 feat : mainpage-animation-add-more
  frontend/src/views/MainPage/MainPage.css
  frontend/src/views/MainPage/MainPage.js
Labels: 추가, 이거고쳐줘, css 수정

#381 Funding money detail page
  frontend/src/views/ProjectDetailPage/DetailFundingStatus.js
  frontend/src/views/ProjectDetailPage/ProjectDetailFundingUser.js
  server/controllers/projectController.js
Labels: 추가, 백엔드

#382 myPage projects opacity unified
  frontend/src/views/ProfilePage/Bookmarks.css
  frontend/src/views/ProfilePage/Common.css
  frontend/src/views/ProfilePage/MyProfile.css
  frontend/src/views/ProfilePage/ParticipatedProjects.js
Labels: css 수정

#384 Detail amount ratio bar
  frontend/src/views/ProjectDetailPage/DetailFundingStatus.css
  frontend/src/views/ProjectDetailPage/DetailFundingStatus.js
Labels: 추가, css 수정

#388 bug : fix create drop down btn (#385)
  frontend/src/components/Header/Header.js
Labels: 버그

#389 feat : 목록 페이지 grid 수정
  frontend/src/components/Layout/ProjectListPageLayout.css
  frontend/src/components/Layout/ProjectListPageLayout.js
Labels: css 수정

#391 메인페이지 애니메이션 추가_css/mainpage animation
  frontend/src/views/MainPage/MainPage.css
  frontend/src/views/MainPage/MainPage.js
Labels: 추가, 확인요망, css 수정

#393 feat: Maincard css animation (#392)
  frontend/src/views/MainPage/Card.js
  frontend/src/views/MainPage/MainPage.css
  frontend/src/views/MainPage/MainPage.js
Labels: css 수정

#394 fix : 마이페이지 나의꿀단지 종료된 프로젝트 꿀단지 클릭 오류 #386
  frontend/src/views/ProfilePage/Bookmarks.css
  frontend/src/views/ProfilePage/Bookmarks.js
Labels: 버그

#396 fix : honeypot-error-again-fix
  frontend/src/views/ProfilePage/Bookmarks.css
  frontend/src/views/ProfilePage/Bookmarks.js
Labels: 버그

#400 feat: CreatePage - onKeyPress (#395)
  frontend/src/components/Layout/CreatePageLayout.js
Labels: 고침

#403 List page search nav connect
  frontend/src/components/Layout/ProjectListPageLayout.js
  frontend/src/components/Layout/SubNav.js
  frontend/src/views/MainPage/MainPage.js
  server/controllers/projectController.js
Labels: 버그, 추가

#404 feat:myPage myHoneyPot scrapButton click issue
  frontend/src/components/Common/Top.css
  frontend/src/views/ProfilePage/Common.css
Labels: css 수정

#406 메인/목록 페이지 카드_ 메인 페이지 query css_css/398 card css edit
  frontend/src/components/Common/ListCard.css
  frontend/src/views/MainPage/Card.js
  frontend/src/views/MainPage/MainPage.css
Labels: 추가, css 수정

#408 My page mobile view edit
  frontend/src/views/ProfilePage/Common.css
Labels: css 수정

#413 feat: CreatePage - number (#412)
  frontend/src/components/Layout/CreatePageLayout.js
Labels: 추가, 백엔드, 기능 개선

#416 feat : sns-sign-up-ui
  frontend/package-lock.json
  frontend/package.json
  frontend/src/img/KakaoTalk_logo.png
  frontend/src/img/google.png
  frontend/src/img/naver.png
  frontend/src/views/LoginPage/LoginPage.css
  frontend/src/views/LoginPage/LoginPage.js
Labels: 추가, 확인요망

#421 feat: ListPage - card animation
  frontend/src/components/Common/ListCard.css
Labels: css 수정

#424 Kakao login error fix and login ui add
  frontend/src/views/LoginPage/KakaoRedirectHandler.js
  frontend/src/views/LoginPage/LoginPage.css
  frontend/src/views/LoginPage/LoginPage.js
  server/controllers/authController.js
Labels: 추가, 백엔드

#425 fix : login-jwt-error-fix
  frontend/src/contexts/AuthContext.js
  frontend/src/views/LoginPage/KakaoRedirectHandler.js
  frontend/src/views/LoginPage/LoginPage.js
  server/controllers/authController.js
  server/controllers/projectController.js
Labels: 고침

#426 메인 페이지 모바일 깨짐_Fix/407 mainpage mobile fix
  frontend/src/views/MainPage/MainPage.css
  frontend/src/views/MainPage/MainPage.js
Labels: css 수정, 고침

#428 feat:createPage targetAmount null edited & myPage flowerImg position …
  frontend/src/views/ProfilePage/Common.css
  frontend/src/views/ProfilePage/MyPosts.js
  frontend/src/views/ProfilePage/MyProfile.css
  frontend/src/views/ProfilePage/MyProfile.js
  frontend/src/views/ProfilePage/ParticipatedProjects.js
  frontend/src/views/ProfilePage/ProfilePage.css
  frontend/src/views/ProfilePage/ProfilePage.js
  frontend/src/views/ProjectDetailPage/DetailFundingStatus.js
Labels: 이거고쳐줘, css 수정, 기능 개선

#431 feat : 닉네임 중복시 - 오류캐치 - 숫자 붙이기 #427
  frontend/src/views/LoginPage/KakaoRedirectHandler.js
  server/controllers/authController.js
Labels: 백엔드, 고침

#434 feat: DatailPage - number comma
  frontend/src/views/ProjectDetailPage/ProjectDetailFundingUser.js
  frontend/src/views/ProjectDetailPage/ProjectDetailPageFunding.js
  frontend/src/views/ProjectDetailPage/ProjectDetailPageWith.js
  frontend/src/views/ProjectDetailPage/ProjectDetailWithUser.js
Labels: 추가

#438 fix: CreatePage - option number modify
  frontend/package-lock.json
  frontend/src/components/Layout/CreatePageLayout.js
Labels: 고침

#440 메인 페이지 icon query 추가_fix : fix icon animation query (#423, #439)
  frontend/src/views/MainPage/MainPage.css
Labels: css 수정, 고침

#444 feat: myPage animation unified & css added
  frontend/src/views/ProfilePage/Common.css
  frontend/src/views/ProfilePage/MyProfile.css
Labels: css 수정

#446 feat: myPage my_honeyPot cards opacity edited & border value edited
  frontend/src/views/ProfilePage/Bookmarks.css
  frontend/src/views/ProfilePage/Common.css
  frontend/src/views/ProfilePage/MyProfile.css
Labels: css 수정

#448 feat : add overlay/query to SNS register modal (#447)
  frontend/src/views/LoginPage/LoginPage.css
  frontend/src/views/LoginPage/LoginPage.js
Labels: 추가, css 수정

#449 feat: CreatePage - input required (#433, #430)
  frontend/src/components/Layout/CreatePageLayout.js
Labels: 추가, 기능 개선

#458 feat : error fix 펀딩 participant_detail total price 합계 금액 오류 #456
  server/controllers/projectController.js
  server/init.sql
Labels: 고침

#459 feature : add copy URL button for detail page (#451)
  frontend/src/views/ProjectDetailPage/DetailButton.css
  frontend/src/views/ProjectDetailPage/DetailButton.js
Labels: 추가, 기능 개선

#460 fix: CreatePage - modify (#457)
  frontend/src/components/Layout/CreatePageLayout.js
Labels: 버그, 고침

#463 edit : edit Nav Subnav and overall css(#462)
  frontend/src/components/Header/Header.css
  frontend/src/components/Header/Header.js
  frontend/src/components/Layout/CreatePageLayout.css
  frontend/src/components/Layout/CreatePageLayout.js
  frontend/src/components/Layout/SubNav.css
  frontend/src/views/LoginPage/LoginPage.css
Labels: 추가, css 수정

#464 fix: CreatePage - calendar issue (#433)
  frontend/src/components/Layout/CreatePageLayout.js
Labels: 중복, 고침

#468 feat : 마이페이지 작성한 글 수정 사항 #467
  docker-compose.yml
  frontend/src/views/ProfilePage/Common.css
  frontend/src/views/ProfilePage/MyProfile.css
  frontend/src/views/ProfilePage/MyProfile.js
  server/controllers/projectController.js
Labels: 추가, css 수정, 고침

#469 fix : css hashtag margin-top
  frontend/src/views/MainPage/MainPage.css
Labels: css 수정

#470 feat : sweet-alert-myprofile-add
  frontend/src/components/Common/Aside.js
  frontend/src/views/ProfilePage/MyProfile.js
Labels: 추가, css 수정

#473 feat: myPage when MyProfile profile-img is edited page reload
  frontend/src/views/ProfilePage/MyProfile.js
Labels: 기능 개선

#476 feat : sweet-alert-add-more
  frontend/src/views/ProfilePage/MyPosts.js
  frontend/src/views/ProfilePage/MyProfile.js
  frontend/src/views/ProfilePage/ParticipatedProjects.js
Labels: 추가

#478 bug-fix : detailpage copy URL btn (#466)
  frontend/src/views/ProjectDetailPage/DetailButton.js
Labels: 고침

#480 fix: CreatePage - option input (#465)
  frontend/src/components/Layout/CreatePageLayout.css
  frontend/src/components/Layout/CreatePageLayout.js
Labels: 버그, 고침

#481 fix : add detailpage maxparticipants (#479)
  frontend/src/views/ProfilePage/Bookmarks.js
  frontend/src/views/ProjectDetailPage/DetailButton.js
  frontend/src/views/ProjectDetailPage/DetailParticipate.js
  frontend/src/views/ProjectDetailPage/ProjectDetailFundingUser.js
  frontend/src/views/ProjectDetailPage/ProjectDetailPage.js
  frontend/src/views/ProjectDetailPage/ProjectDetailPageFunding.js
  frontend/src/views/ProjectDetailPage/ProjectDetailPageWith.js
  frontend/src/views/ProjectDetailPage/ProjectDetailWithUser.js
Labels: 고침

#483 css : unify sweet alert css (#441)
  frontend/src/components/Common/Aside.js
  frontend/src/components/Common/SweetAlert.css
  frontend/src/img/KakaoTalk_logo.png
  frontend/src/img/naver.png
  frontend/src/views/LoginPage/LoginPage.css
  frontend/src/views/LoginPage/LoginPage.js
  frontend/src/views/MainPage/MainPage.css
  frontend/src/views/ProfilePage/MyPosts.js
  frontend/src/views/ProfilePage/MyProfile.js
  frontend/src/views/ProfilePage/ParticipatedProjects.js
  frontend/src/views/ProjectDetailPage/DetailAgree.css
  frontend/src/views/ProjectDetailPage/ProjectDetailFundingUser.js
  frontend/src/views/ProjectDetailPage/ProjectDetailWithUser.js
  frontend/src/views/RegisterPage/RegisterPage.js
Labels: 추가, css 수정

#494 Detail page alert add css fix
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/src/components/Layout/BackGroundGrid.css
  frontend/src/views/ProjectDetailPage/DetailFundingStatus.js
  frontend/src/views/ProjectDetailPage/DetailUserInfo.js
  frontend/src/views/ProjectDetailPage/ProjectDetailFundingUser.js
  frontend/src/views/ProjectDetailPage/ProjectDetailPage.css
  frontend/src/views/ProjectDetailPage/ProjectDetailPageFunding.js
Labels: 추가, css 수정, 고침

#496 feature : Add info box / redirect to login page when logged out to Card (#487)
  frontend/src/components/Common/ListCard.js
  frontend/src/img/scrap_none.svg
  frontend/src/views/MainPage/Card.js
  frontend/src/views/MainPage/MainPage.css
  frontend/src/views/MainPage/MainPage.js
Labels: 추가, css 수정, 기능 개선

#498 feat : slick-slider-fix-and-add
  frontend/src/views/MainPage/MainPage.js
Labels: 추가

#499 fix: CreatePage and ProjectPage (#486)
  frontend/src/components/Layout/CreatePageLayout.css
  frontend/src/components/Layout/CreatePageLayout.js
  frontend/src/views/ProjectDetailPage/ProjectDetailPageWith.js
Labels: css 수정, 기능 개선, 고침

#502 myPage-edited
  frontend/src/components/Common/Top.css
  frontend/src/views/ProfilePage/Common.css
  frontend/src/views/ProfilePage/MyPosts.js
  frontend/src/views/ProfilePage/ParticipatedProjects.js
  frontend/src/views/ProfilePage/ProfilePage.css
Labels: css 수정, 기능 개선

#507 feat:myPage several edit
  frontend/src/components/Common/Aside.js
  frontend/src/components/Common/Top.css
  frontend/src/views/ProfilePage/Bookmarks.css
  frontend/src/views/ProfilePage/Bookmarks.js
  frontend/src/views/ProfilePage/Common.css
  frontend/src/views/ProfilePage/MyPosts.js
  frontend/src/views/ProfilePage/MyProfile.css
  frontend/src/views/ProfilePage/MyProfile.js
  frontend/src/views/ProfilePage/ParticipatedProjects.js
Labels: 확인요망, css 수정

#508 Mypage select box sorting
  frontend/package-lock.json
  frontend/package.json
  frontend/src/views/ProfilePage/CardSorting.js
  frontend/src/views/ProfilePage/MyPosts.js
  frontend/src/views/ProfilePage/ParticipatedProjects.js
Labels: 추가

#509 fix: CreatePage - min and max modify(#432)
  frontend/src/components/Layout/CreatePageLayout.js
Labels: 추가, 기능 개선

#511 feat : 랭킹섹션 추가 #18
  frontend/src/views/MainPage/MainPage.js
  server/controllers/projectController.js
  server/routes/projectRoutes.js
Labels: 추가

#513 css : add mypage honeypot overlay, change border width to box-shadow
  frontend/src/components/Common/Aside.css
  frontend/src/components/Common/Top.css
  frontend/src/views/ProfilePage/Bookmarks.css
  frontend/src/views/ProfilePage/Bookmarks.js
  frontend/src/views/ProfilePage/Common.css
  frontend/src/views/ProfilePage/MyProfile.css
Labels: css 수정

#515 My page bookmarks sorting
  frontend/src/views/ProfilePage/Bookmarks.js
  frontend/src/views/ProfilePage/CardSorting.js
  frontend/src/views/ProfilePage/MyPosts.js
  frontend/src/views/ProfilePage/ParticipatedProjects.js
Labels: 추가, 이거고쳐줘, css 수정

#516 feat : hashtag-link-add
  frontend/src/views/MainPage/MainPage.css
  frontend/src/views/MainPage/MainPage.js
  frontend/src/views/ProjectDetailPage/DetailHashtag.css
  frontend/src/views/ProjectDetailPage/DetailHashtag.js
  server/init.sql
Labels: 추가

#517 feat : add initialize scroll component (#495)
  frontend/src/App.js
  frontend/src/components/Routing/ScrollToTop.js
Labels: 추가, 기능 개선

#518 feat : 나의꿀단지 정렬 오류 , css 수정 #514
  frontend/src/views/ProfilePage/Bookmarks.css
  frontend/src/views/ProfilePage/Bookmarks.js
  frontend/src/views/ProfilePage/CardSorting.js
  frontend/src/views/ProfilePage/MyPosts.js
Labels: 추가, 고침

#521 CreatePage option bug fix
  frontend/src/components/Layout/CreatePageLayout.js
Labels: 고침

#528 feat: MainPage and Header txt modify
  frontend/src/components/Header/Header.css
  frontend/src/components/Header/Header.js
  frontend/src/views/MainPage/MainPage.js
Labels: 문서, css 수정

#527 feat: myPage detail modification
  frontend/src/views/ProfilePage/Bookmarks.css
  frontend/src/views/ProfilePage/Common.css
Labels: css 수정

#529 css : detail changes on mainpage-main-button
  frontend/src/views/MainPage/MainPage.css
  frontend/src/views/MainPage/MainPage.js
Labels: css 수정

#536 fix : 마이페이지 동행 참여자 업데이트 #531
  frontend/src/views/ProjectDetailPage/ProjectDetailWithUser.js
  server/controllers/projectController.js
Labels: 고침

#539 feat : 목록 페이지 카드 그리드 쿼리 추가 #538
  frontend/src/components/Common/ListCard.css
  frontend/src/components/Layout/ProjectListPageLayout.css
  frontend/src/components/Layout/ProjectListPageLayout.js
Labels: 추가, css 수정

#552 css : add query to pagination (#551)
  frontend/src/components/Common/Pagination.css
  frontend/src/components/Layout/ProjectListPageLayout.css
Labels: css 수정

#553 myPage alert message and button text edited
  frontend/src/views/ProfilePage/Common.css
  frontend/src/views/ProfilePage/MyPosts.js
  frontend/src/views/ProfilePage/MyProfile.css
  frontend/src/views/ProfilePage/ParticipatedProjects.js
Labels: css 수정, 기능 개선

#554 Fix/534 modal bug
  frontend/src/views/LoginPage/LoginPage.js
Labels: 고침

#555 feat : 목록 페이지 타이틀 수정 #520
  frontend/src/components/Layout/ProjectListPageLayout.js
  frontend/src/components/Layout/SubNav.js
  frontend/src/views/MainPage/MainPage.js
Labels: 추가

#560 feat: when myPage-category clicked, scrollPosition will be fixed
  frontend/src/components/Common/Aside.js
  frontend/src/views/ProfilePage/Bookmarks.css
Labels: 기능 개선

#565 hox-fix : add important to sweet alert
  frontend/src/components/Common/SweetAlert.css
Labels: 추가

#566 Hot Fix : add important to sweet alert
  frontend/src/components/Common/SweetAlert.css
Labels: css 수정
